# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
# Following the example in https://www.taniarascia.com/make-a-static-website-with-jekyll/

# Site settings
lang: en-US
title: yogen
alt_title: We are yogen
email: info@yogen.io
description: > # this means to ignore newlines until "baseurl:"
  We are a one-stop shop for your Data Science needs.
  We can help your business make the most of your data, or we can teach
  you how to do it yourself.
  We solve your problems in the Machine Learning, Big Data, or Visualization
  spaces.
short_description: We are a one-stop shop for your Data Science needs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yogen.io" # the base hostname & protocol for your site
github_username: yogen-io
author:
  name: "Daniel Mateos"
  title: "Data Scientist and educator, Founder at yogen.io"
  github: "https://github.com/danimateos"
  linkedin: "https://www.linkedin.com/in/daniel-mateos-san-martín-b02aa956/"
logo: /assets/logo_round.svg

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
gems:
#  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Google analytics:
google_analytics: UA-96930235-1
  
# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
